// Auto-generated by weekly data refresh - 2026-03-09
// Sources: AER ST102, AESO CSD Report, Alberta Open Data

export const LAST_UPDATED = '2026-03-09';

export interface AerGasFacility {
  facilityId: string;
  facilityName: string;
  operatorName: string;
  facilityType: 'GAS_PLANT';
  facilitySubtype: string;
  licenceNumber: string;
  location: string;
  municipality: string;
  status: 'ACTIVE';
  source: string;
  sourceUrl: string;
}

export interface AesoGenerationByFuel {
  fuelType: string;
  capacityMW: number;
  generationMW: number;
}

export interface AesoGridSnapshot {
  timestamp: string;
  albertaInternalLoadMW: number;
  netToGridGenerationMW: number;
  interchangeMW: number;
  poolPricePerMWh: number;
  rolling30DayAvgPerMWh: number | null;
  generationByFuel: AesoGenerationByFuel[];
  source: string;
  sourceUrl: string;
}

export interface MunicipalEnergyStat {
  municipality: string;
  gasProductionE3M3: number;
  year: number;
  source: string;
  sourceUrl: string;
}

export interface DataSource {
  name: string;
  url: string;
  lastFetched: string;
  description: string;
}

// AER ST102 Active Gas Plants (20 entries)
export const aerGasFacilities: AerGasFacility[] = [
  {
    facilityId: 'ABGP0001153',
    facilityName: 'Ferrybank 02-01 Gas Plant',
    operatorName: 'Tourmaline Oil Corp.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sweet',
    licenceNumber: 'F9522',
    location: '02-01-044-28W4',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001158',
    facilityName: 'Pennwest Pembina (Sub #1)',
    operatorName: 'Ricochet Oil Corp.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sweet',
    licenceNumber: 'F22272',
    location: '09-25-048-07W5',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001161',
    facilityName: 'Mobil Pembina',
    operatorName: 'Ricochet Oil Corp.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Acid Gas Flaring < 1 T/D Sulphur',
    licenceNumber: 'F11364',
    location: '09-16-049-08W5',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001167',
    facilityName: 'Crestar Huxley',
    operatorName: 'Pine Cliff Energy Ltd.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sweet',
    licenceNumber: 'F4710',
    location: '06-17-034-24W4',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001169',
    facilityName: 'Dunvegan 15-3-81-4w6',
    operatorName: 'Canadian Natural Resources Limited',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sweet',
    licenceNumber: 'F16714',
    location: '15-03-081-04W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001184',
    facilityName: 'Knopcik 9-10-74-11w6',
    operatorName: 'Canadian Natural Resources Limited',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sweet',
    licenceNumber: 'F15494',
    location: '09-10-074-11W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001191',
    facilityName: 'Barrel Turin 12-19-12-18w4',
    operatorName: 'Barrel Oil Corp.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Acid Gas Injection',
    licenceNumber: 'F911',
    location: '12-19-012-18W4',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001192',
    facilityName: 'Swan Hills',
    operatorName: 'Cardinal Energy Ltd.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Acid Gas Flaring < 1 T/D Sulphur',
    licenceNumber: 'F14994',
    location: '01-08-070-10W5',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001222',
    facilityName: 'Cutbank 7-16-62-8w6',
    operatorName: 'Pembina Gas Infrastructure Inc.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sweet',
    licenceNumber: 'F13915',
    location: '07-16-062-08W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001268',
    facilityName: 'Rosevear 16-11 Gas Plant',
    operatorName: 'Tourmaline Oil Corp.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sulphur Recovery',
    licenceNumber: 'F12454',
    location: '16-11-054-15W5',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001296',
    facilityName: 'Teepee Creek 07-02-074-04w6',
    operatorName: 'Canadian Natural Resources Limited',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sulphur Recovery',
    licenceNumber: 'F15443',
    location: '07-02-074-04W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0001360',
    facilityName: 'Petro-Can Hanlan',
    operatorName: 'Canlin Resources Partnership',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sulphur Recovery',
    licenceNumber: 'F11504',
    location: '15-02-049-20W5',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0106720',
    facilityName: 'Harmattan Fractionation',
    operatorName: 'AltaGas Ltd.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Fractionation',
    licenceNumber: 'F4285',
    location: '09-27-031-04W5',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0107835',
    facilityName: 'Aav Glacier 05-02-076-12w6 Gp',
    operatorName: 'Advantage Energy Ltd.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Acid Gas Injection',
    licenceNumber: 'F40420',
    location: '05-02-076-12W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0120344',
    facilityName: '10-7 Gas Processing Plant',
    operatorName: 'ARC Resources Ltd.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sweet',
    licenceNumber: 'F43131',
    location: '10-07-067-24W5',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0123090',
    facilityName: 'Gordondale Gas Plant',
    operatorName: 'Birchcliff Energy Ltd.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Acid Gas Injection',
    licenceNumber: 'F43105',
    location: '16-31-078-11W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0150355',
    facilityName: 'Keyera Wapiti Gas Plant',
    operatorName: 'Keyera Energy Ltd.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Acid Gas Injection',
    licenceNumber: 'F47965',
    location: '03-19-067-07W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0150386',
    facilityName: 'Keyera Pipestone 04-07 Gas Plant',
    operatorName: 'Keyera Energy Ltd.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Acid Gas Flaring < 1 T/D Sulphur',
    licenceNumber: 'F50089',
    location: '04-07-073-08W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0150704',
    facilityName: 'Wapiti Gas Plant',
    operatorName: 'Pembina Gas Infrastructure Inc.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Sulphur Recovery',
    licenceNumber: 'F49284',
    location: '07-35-067-07W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
  {
    facilityId: 'ABGP0152315',
    facilityName: 'Pipestone 12-35-070-09w6 Gas Plant',
    operatorName: 'AltaGas Ltd.',
    facilityType: 'GAS_PLANT',
    facilitySubtype: 'Gas Plant Acid Gas Injection',
    licenceNumber: 'F51047',
    location: '12-35-070-09W6',
    municipality: '',
    status: 'ACTIVE',
    source: 'AER ST102',
    sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
  },
];

// AESO Grid Snapshot - 2026-03-09 06:16 MDT
export const aesoGridSnapshot: AesoGridSnapshot = {
  timestamp: '2026-03-09T06:16:00-07:00',
  albertaInternalLoadMW: 10418,
  netToGridGenerationMW: 7719,
  interchangeMW: -198,
  poolPricePerMWh: 19.06,
  rolling30DayAvgPerMWh: 25.39,
  generationByFuel: [
    { fuelType: 'COGENERATION',          capacityMW: 6137, generationMW: 3464 },
    { fuelType: 'WIND',                  capacityMW: 5684, generationMW: 2898 },
    { fuelType: 'COMBINED CYCLE (GAS)',  capacityMW: 3974, generationMW: 2801 },
    { fuelType: 'GAS FIRED STEAM',       capacityMW: 3078, generationMW: 579  },
    { fuelType: 'SOLAR',                 capacityMW: 1870, generationMW: 0    },
    { fuelType: 'SIMPLE CYCLE (GAS)',    capacityMW: 998,  generationMW: 94   },
    { fuelType: 'HYDRO',                 capacityMW: 899,  generationMW: 102  },
    { fuelType: 'OTHER (BIOMASS/WASTE)', capacityMW: 479,  generationMW: 282  },
    { fuelType: 'ENERGY STORAGE',        capacityMW: 190,  generationMW: 0    },
  ],
  source: 'AESO Public Data',
  sourceUrl: 'https://www.aeso.ca/market/market-and-system-reporting/data-requests/current-supply-and-demand/',
};

// Municipal Energy Stats - Top 6 by Gas Production (2023, E3M3)
export const municipalEnergyStats: MunicipalEnergyStat[] = [
  {
    municipality: 'Greenview No. 16',
    gasProductionE3M3: 39503.7,
    year: 2023,
    source: 'Alberta Open Data - Natural Gas Production by Municipality',
    sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality',
  },
  {
    municipality: 'Yellowhead County',
    gasProductionE3M3: 21776.6,
    year: 2023,
    source: 'Alberta Open Data - Natural Gas Production by Municipality',
    sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality',
  },
  {
    municipality: 'Clearwater County',
    gasProductionE3M3: 14237.6,
    year: 2023,
    source: 'Alberta Open Data - Natural Gas Production by Municipality',
    sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality',
  },
  {
    municipality: 'Saddle Hills County',
    gasProductionE3M3: 11509.5,
    year: 2023,
    source: 'Alberta Open Data - Natural Gas Production by Municipality',
    sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality',
  },
  {
    municipality: 'Grande Prairie County No. 1',
    gasProductionE3M3: 10766.6,
    year: 2023,
    source: 'Alberta Open Data - Natural Gas Production by Municipality',
    sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality',
  },
  {
    municipality: 'Bonnyville No. 87',
    gasProductionE3M3: 861.1,
    year: 2023,
    source: 'Alberta Open Data - Natural Gas Production by Municipality',
    sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality',
  },
];

// Data Sources Registry
export const dataSources: DataSource[] = [
  {
    name: 'AER ST102 Active Facilities',
    url: 'https://www.aer.ca/data/codes/ActiveFacility.txt',
    lastFetched: '2026-03-09',
    description: 'Alberta Energy Regulator active facilities list including gas plants, batteries, and compressor stations.',
  },
  {
    name: 'AESO Current Supply and Demand',
    url: 'https://www.aeso.ca/market/market-and-system-reporting/data-requests/current-supply-and-demand/',
    lastFetched: '2026-03-09',
    description: 'Alberta Electric System Operator real-time grid supply/demand summary including AIL, interchange, and generation by fuel type.',
  },
  {
    name: 'Alberta Open Data - Natural Gas Production by Municipality',
    url: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality',
    lastFetched: '2026-03-09',
    description: 'Annual natural gas production by municipal district sourced from Alberta Energy Regulator via Alberta Regional Dashboard.',
  },
];
