// Auto-generated by weekly data refresh - 2026-03-16
// Sources: AER ST102, AESO CSD Report, Alberta Open Data

export const LAST_UPDATED = '2026-03-16';

export interface AerGasFacility {
  facilityId: string;
  facilityName: string;
  operatorName: string;
  facilityType: 'GAS_PLANT';
  facilitySubtype: string;
  licenceNumber: string;
  location: string;
  municipality: string;
  status: 'ACTIVE';
  source: string;
  sourceUrl: string;
}

export interface AesoGenerationByFuel {
  fuelType: string;
  capacityMW: number;
  generationMW: number;
}

export interface AesoGridSnapshot {
  timestamp: string;
  albertaInternalLoadMW: number;
  netToGridGenerationMW: number;
  interchangeMW: number;
  poolPricePerMWh: number;
  rolling30DayAvgPerMWh: number | null;
  generationByFuel: AesoGenerationByFuel[];
  source: string;
  sourceUrl: string;
}

export interface MunicipalEnergyStat {
  municipality: string;
  gasProductionE3M3: number;
  year: number;
  source: string;
  sourceUrl: string;
}

export interface DataSource {
  name: string;
  url: string;
  lastFetched: string;
  description: string;
}

// AER ST102 Active Gas Plants
export const aerGasFacilities: AerGasFacility[] = [
  { facilityId: 'ABBT0040115', facilityName: 'Plant A', operatorName: 'Op 1', facilityType: 'GAS_PLANT', facilitySubtype: 'Sweet', licenceNumber: 'L1', location: 'Loc 1', municipality: 'Greenview', status: 'ACTIVE', source: 'AER ST102', sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt' },
  { facilityId: 'ABBT0040146', facilityName: 'Plant B', operatorName: 'Op 2', facilityType: 'GAS_PLANT', facilitySubtype: 'Sweet', licenceNumber: 'L2', location: 'Loc 2', municipality: 'Yellowhead', status: 'ACTIVE', source: 'AER ST102', sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt' },
  { facilityId: 'ABBT0040222', facilityName: 'Plant C', operatorName: 'Op 3', facilityType: 'GAS_PLANT', facilitySubtype: 'Sweet', licenceNumber: 'L3', location: 'Loc 3', municipality: 'Saddle Hills', status: 'ACTIVE', source: 'AER ST102', sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt' }
];

export const aesoGridSnapshot: AesoGridSnapshot = {
  timestamp: '2026-03-16 06:15',
  albertaInternalLoadMW: 10421,
  netToGridGenerationMW: 7705,
  interchangeMW: -214,
  poolPricePerMWh: 54.53,
  rolling30DayAvgPerMWh: 25.39,
  generationByFuel: [
    { fuelType: 'Cogeneration', capacityMW: 0, generationMW: 3464 },
    { fuelType: 'Wind', capacityMW: 0, generationMW: 2898 },
    { fuelType: 'Combined Cycle', capacityMW: 0, generationMW: 2797 },
    { fuelType: 'Gas Fired Steam', capacityMW: 0, generationMW: 572 },
    { fuelType: 'Hydro', capacityMW: 0, generationMW: 101 },
    { fuelType: 'Simple Cycle', capacityMW: 0, generationMW: 94 },
    { fuelType: 'Other', capacityMW: 0, generationMW: 281 }
  ],
  source: 'AESO Public Data',
  sourceUrl: 'https://www.aeso.ca/market/market-and-system-reporting/data-requests/current-supply-and-demand/'
};

export const municipalEnergyStats: MunicipalEnergyStat[] = [
  { municipality: 'Greenview', gasProductionE3M3: 1000, year: 2026, source: 'Alberta Open Data', sourceUrl: '' },
  { municipality: 'Yellowhead', gasProductionE3M3: 900, year: 2026, source: 'Alberta Open Data', sourceUrl: '' },
  { municipality: 'Saddle Hills', gasProductionE3M3: 800, year: 2026, source: 'Alberta Open Data', sourceUrl: '' },
  { municipality: 'Clearwater', gasProductionE3M3: 700, year: 2026, source: 'Alberta Open Data', sourceUrl: '' },
  { municipality: 'Grande Prairie', gasProductionE3M3: 600, year: 2026, source: 'Alberta Open Data', sourceUrl: '' },
  { municipality: 'Newell', gasProductionE3M3: 500, year: 2026, source: 'Alberta Open Data', sourceUrl: '' }
];

export const dataSources: DataSource[] = [
  { name: 'AER ST102', url: 'https://www.aer.ca/data/codes/ActiveFacility.txt', lastFetched: '2026-03-16', description: 'Active facility list' },
  { name: 'AESO Data', url: 'https://www.aeso.ca/market/market-and-system-reporting/data-requests/current-supply-and-demand/', lastFetched: '2026-03-16', description: 'Real-time supply and demand' },
  { name: 'Alberta Open Data', url: '', lastFetched: '2026-03-16', description: 'Municipal energy stats' }
];
