// Auto-generated by weekly data refresh - 2026-03-23
// Sources: AER ST102, AESO CSD Report, Alberta Open Data

export const LAST_UPDATED = '2026-03-23';

export interface AerGasFacility {
  facilityId: string;
  facilityName: string;
  operatorName: string;
  facilityType: 'GAS_PLANT';
  facilitySubtype: string;
  licenceNumber: string;
  location: string;
  municipality: string;
  status: 'ACTIVE';
  source: string;
  sourceUrl: string;
}

export interface AesoGenerationByFuel {
  fuelType: string;
  capacityMW: number;
  generationMW: number;
}

export interface AesoGridSnapshot {
  timestamp: string;
  albertaInternalLoadMW: number;
  netToGridGenerationMW: number;
  interchangeMW: number;
  poolPricePerMWh: number;
  rolling30DayAvgPerMWh: number | null;
  generationByFuel: AesoGenerationByFuel[];
  source: string;
  sourceUrl: string;
}

export interface MunicipalEnergyStat {
  municipality: string;
  gasProductionE3M3: number;
  year: number;
  source: string;
  sourceUrl: string;
}

export interface DataSource {
  name: string;
  url: string;
  lastFetched: string;
  description: string;
}

// AER ST102 Active Gas Plants
export const aerGasFacilities: AerGasFacility[] = [
  { facilityId: 'ABBT0040222', facilityName: 'Poco Threehick 8-32', operatorName: 'Vantage Point Resources Inc.', facilityType: 'GAS_PLANT', facilitySubtype: 'Gas Multiwell Group Battery', licenceNumber: 'F5116', location: '1 32 35 26 W4', municipality: '', status: 'ACTIVE', source: 'AER ST102', sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt' },
  { facilityId: 'ABBT0030001', facilityName: 'Morgan Abee Group #2', operatorName: 'Canlin Resources Partnership', facilityType: 'GAS_PLANT', facilitySubtype: 'Gas Multiwell Group Battery', licenceNumber: '', location: '1 32 61 22 W4', municipality: '', status: 'ACTIVE', source: 'AER ST102', sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt' },
  { facilityId: 'ABBT0040115', facilityName: 'Barrel Niton 06-19-054-11w5', operatorName: 'Barrel Oil Corp.', facilityType: 'GAS_PLANT', facilitySubtype: 'Gas Single-Well Battery', licenceNumber: 'W 0100031', location: '6 19 54 11 W5', municipality: '', status: 'ACTIVE', source: 'AER ST102', sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt' },
  { facilityId: 'ABBT0040146', facilityName: 'Bowtex Crystal 01-04', operatorName: 'Questfire Energy Corp.', facilityType: 'GAS_PLANT', facilitySubtype: 'Gas Multiwell Group Battery', licenceNumber: 'F40798', location: '1 4 47 3 W5', municipality: '', status: 'ACTIVE', source: 'AER ST102', sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt' },
  { facilityId: 'ABBT0040188', facilityName: 'Pci Gilby 04-34', operatorName: 'Canlin Resources Partnership', facilityType: 'GAS_PLANT', facilitySubtype: 'Gas Multiwell Group Battery', licenceNumber: 'F43009', location: '4 34 41 4 W5', municipality: '', status: 'ACTIVE', source: 'AER ST102', sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt' },
  { facilityId: 'ABBT0040195', facilityName: 'Phillips Salter 4-36', operatorName: 'Canlin Resources Partnership', facilityType: 'GAS_PLANT', facilitySubtype: 'Gas Multiwell Effluent Measurement Battery', licenceNumber: '', location: '4 36 26 8 W5', municipality: '', status: 'ACTIVE', source: 'AER ST102', sourceUrl: 'https://www.aer.ca/data/codes/ActiveFacility.txt' }
];

// AESO Current Supply & Demand Snapshot
export const aesoGridSnapshot: AesoGridSnapshot = {
  timestamp: '2026-03-23T06:04:00-06:00',
  albertaInternalLoadMW: 10561,
  netToGridGenerationMW: 7485,
  interchangeMW: -208,
  poolPricePerMWh: 15.01,
  rolling30DayAvgPerMWh: 25.39,
  generationByFuel: [
    { fuelType: 'Cogeneration', capacityMW: 6122, generationMW: 4765 },
    { fuelType: 'Wind', capacityMW: 5684, generationMW: 1501 },
    { fuelType: 'Combined Cycle', capacityMW: 3974, generationMW: 2705 },
    { fuelType: 'Gas Fired Steam', capacityMW: 3078, generationMW: 834 },
    { fuelType: 'Simple Cycle', capacityMW: 1014, generationMW: 109 },
    { fuelType: 'Hydro', capacityMW: 899, generationMW: 146 },
    { fuelType: 'Solar', capacityMW: 1870, generationMW: 0 },
    { fuelType: 'Energy Storage', capacityMW: 190, generationMW: 3 },
    { fuelType: 'Other', capacityMW: 479, generationMW: 290 }
  ],
  source: 'AESO Public Data',
  sourceUrl: 'https://www.aeso.ca/market/market-and-system-reporting/data-requests/current-supply-and-demand/'
};

// Municipal Energy Statistics (Top 6 by gas production 2024)
export const municipalEnergyStats: MunicipalEnergyStat[] = [
  { municipality: 'Greenview No. 16', gasProductionE3M3: 42059316.9, year: 2024, source: 'Alberta Open Data', sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality' },
  { municipality: 'Yellowhead County', gasProductionE3M3: 21776608.1, year: 2024, source: 'Alberta Open Data', sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality' },
  { municipality: 'Clearwater County', gasProductionE3M3: 13736639.9, year: 2024, source: 'Alberta Open Data', sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality' },
  { municipality: 'Saddle Hills County', gasProductionE3M3: 11789122.3, year: 2024, source: 'Alberta Open Data', sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality' },
  { municipality: 'Grande Prairie County No. 1', gasProductionE3M3: 11207306.9, year: 2024, source: 'Alberta Open Data', sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality' },
  { municipality: 'Wheatland County', gasProductionE3M3: 2573054.6, year: 2024, source: 'Alberta Open Data', sourceUrl: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality' }
];

// Data Sources
export const dataSources: DataSource[] = [
  { name: 'AER ST102', url: 'https://www.aer.ca/data/codes/ActiveFacility.txt', lastFetched: '2026-03-23', description: 'Active facility registry from Alberta Energy Regulator' },
  { name: 'AESO CSD Report', url: 'https://www.aeso.ca/market/market-and-system-reporting/data-requests/current-supply-and-demand/', lastFetched: '2026-03-23', description: 'Real-time grid supply and demand data from Alberta Electric System Operator' },
  { name: 'Alberta Open Data', url: 'https://open.alberta.ca/opendata/natural-gas-production-by-municipality', lastFetched: '2026-03-23', description: 'Natural gas production statistics by municipality' }
];
